work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN

# feeder
feeder: feeder.feeder_exam_ds.FeederExamDs
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 50 
  data_path: /content/exam_action_ds/train
test_feeder_args:
  data_path: /content/exam_action_ds/val
  random_choose: True
  window_size: 50

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 4
  edge_importance_weighting: True
  graph_args:
    layout: 'exam'
    strategy: 'spatial'

# training
device: [0]
batch_size: 256 
test_batch_size: 256

#optim
base_lr: 0.001
step: [100, 200, 300, 400]
num_epoch: 500
#base_lr: 0.01
#step: [200, 300, 400, 500]
#num_epoch: 500



