work_dir: ./work_dir/recognition/kinetics_skeleton/ST_GCN

# feeder
feeder: feeder.feeder_exam_ds.FeederExamDs
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 50 
  data_path: /mnt/hdd10tb/Students/phonghh/dataset/action/exam/exam_action_ds/train
test_feeder_args:
  data_path: /mnt/hdd10tb/Students/phonghh/dataset/action/exam/exam_action_ds/val
  random_choose: True
  window_size: 50

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 4
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: [5]
batch_size: 256 
test_batch_size: 256

#optim
base_lr: 0.1
step: [20, 30, 40, 50]
num_epoch: 50



